from . import help
from . import start
from . import darslik
from . import backend
from . import english
from . import admin
from . import algoritm
from . import qushimcha_malumot
from . import test_file
from . import nesting_darslik
